package code

import (
	"os"
	"path/filepath"
	"testing"
)

// ── Go gRPC scanner ───────────────────────────────────────────────────────────

func TestScanGoGRPC_FindsMethods(t *testing.T) {
	dir := t.TempDir()
	content := `// Code generated by protoc-gen-go-grpc.
package pb

type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePayment(ctx context.Context, in *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentServiceServer) GetPayment(ctx context.Context, in *GetPaymentRequest) (*GetPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayment not implemented")
}
func (UnimplementedPaymentServiceServer) RefundPayment(ctx context.Context, in *RefundRequest) (*RefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundPayment not implemented")
}
`
	write(t, dir, "payment_grpc.pb.go", content)

	scanner := NewGRPCScanner(dir)
	methods, err := scanner.Scan()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := map[string]bool{"CreatePayment": true, "GetPayment": true, "RefundPayment": true}
	for _, m := range methods {
		if m.Service != "PaymentService" {
			t.Errorf("unexpected service %q", m.Service)
		}
		delete(want, m.Method)
	}
	if len(want) > 0 {
		t.Errorf("missing methods: %v", want)
	}
}

func TestScanGoGRPC_NonGRPCFilesIgnored(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "handler.go", `
func (s *Server) CreatePayment(ctx context.Context, req *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return &CreatePaymentResponse{}, nil
}
`)
	scanner := NewGRPCScanner(dir)
	methods, err := scanner.Scan()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	// Non-generated file should not be matched.
	if len(methods) != 0 {
		t.Errorf("expected no methods from non-grpc file, got %d", len(methods))
	}
}

// ── Python gRPC scanner ───────────────────────────────────────────────────────

func TestScanPythonGRPC_FindsMethods(t *testing.T) {
	dir := t.TempDir()
	content := `# Generated by the gRPC Python protocol compiler plugin.

class PaymentServiceServicer(object):
    """The greeting service definition."""

    def CreatePayment(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

    def GetPayment(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)


class OtherServiceServicer(object):
    def DoThing(self, request, context):
        pass
`
	write(t, dir, "payment_pb2_grpc.py", content)

	scanner := NewGRPCScanner(dir)
	methods, err := scanner.Scan()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	byService := indexMethods(methods)
	if len(byService["PaymentService"]) != 2 {
		t.Errorf("want 2 PaymentService methods, got %d", len(byService["PaymentService"]))
	}
	if len(byService["OtherService"]) != 1 {
		t.Errorf("want 1 OtherService method, got %d", len(byService["OtherService"]))
	}
}

// ── .NET gRPC scanner ─────────────────────────────────────────────────────────

func TestScanDotNetGRPC_FindsMethods(t *testing.T) {
	dir := t.TempDir()
	content := `// <auto-generated>
namespace Payments.Grpc
{
    public abstract partial class PaymentServiceBase
    {
        public virtual Task<CreatePaymentResponse> CreatePayment(CreatePaymentRequest request, ServerCallContext context)
        {
            throw new RpcException(new Status(StatusCode.Unimplemented, ""));
        }

        public virtual Task<GetPaymentResponse> GetPayment(GetPaymentRequest request, ServerCallContext context)
        {
            throw new RpcException(new Status(StatusCode.Unimplemented, ""));
        }
    }
}
`
	write(t, dir, "PaymentGrpc.cs", content)

	scanner := NewGRPCScanner(dir)
	methods, err := scanner.Scan()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	byService := indexMethods(methods)
	if _, ok := byService["PaymentService"]["CreatePayment"]; !ok {
		t.Errorf("expected CreatePayment in PaymentService, got %v", byService)
	}
	if _, ok := byService["PaymentService"]["GetPayment"]; !ok {
		t.Errorf("expected GetPayment in PaymentService, got %v", byService)
	}
}

// ── Java gRPC scanner ─────────────────────────────────────────────────────────

func TestScanJavaGRPC_FindsMethods(t *testing.T) {
	dir := t.TempDir()
	content := `// Generated by the protocol buffer compiler.
public final class PaymentServiceGrpc {

  public static abstract class PaymentServiceImplBase implements io.grpc.BindableService {

    public void createPayment(CreatePaymentRequest request,
        io.grpc.stub.StreamObserver<CreatePaymentResponse> responseObserver) {
      io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall(getCreatePaymentMethod(), responseObserver);
    }

    public void getPayment(GetPaymentRequest request,
        io.grpc.stub.StreamObserver<GetPaymentResponse> responseObserver) {
      io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall(getGetPaymentMethod(), responseObserver);
    }
  }
}
`
	write(t, dir, "PaymentServiceGrpc.java", content)

	scanner := NewGRPCScanner(dir)
	methods, err := scanner.Scan()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	byService := indexMethods(methods)
	// Java method names are camelCase; scanner capitalises to PascalCase.
	if _, ok := byService["PaymentService"]["CreatePayment"]; !ok {
		t.Errorf("expected CreatePayment (capitalised), got %v", byService["PaymentService"])
	}
	if _, ok := byService["PaymentService"]["GetPayment"]; !ok {
		t.Errorf("expected GetPayment (capitalised), got %v", byService["PaymentService"])
	}
}

// ── helpers ───────────────────────────────────────────────────────────────────

func write(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

// indexMethods indexes GRPCMethod results as service → method → GRPCMethod.
func indexMethods(ms []GRPCMethod) map[string]map[string]GRPCMethod {
	idx := make(map[string]map[string]GRPCMethod)
	for _, m := range ms {
		if idx[m.Service] == nil {
			idx[m.Service] = make(map[string]GRPCMethod)
		}
		idx[m.Service][m.Method] = m
	}
	return idx
}
